### ISSUE TITLE
Add custom display property

### ISSUE THREAD

**Issue by alexzerah** [Alex-D/Cookies-EU-banner#48]
👋 Hi everyone, 

First of all, thanks for your really cool lib! 

As a web developper I need a way to add custom css `display`.
For exemple `display: flex` instead of `display: block`.

It can be really cool 🤘

Thanks again

**Comment by Alex-D** [comment]
Hey!

So you basically just need an option to change the value set in this line :
https://github.com/Alex-D/Cookies-EU-banner/blob/6e8c083864f17b72f8cdfcb79690d97d0ff24554/src/cookies-eu-banner.js#L81

**Comment by alexzerah** [comment]
Yeah, I was thinking about updating outside the library, but I solved the problem I was.
Thanks

**Comment by Alex-D** [comment]
You can hack it with something like

```css
#cookies-eu-banner[style*="display: block"] {
  display: flex !important;
}
```
